name: Test filtering Matrix jobs

on:
  merge_group:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    strategy:
      fail-fast: false
      matrix:
        bits: [32, 64]
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Report
        run: echo "Setup completed"
  build:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'merge_group' || matrix.bits == 64 }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Filter
        run: exit 0
      - name: Task
        run: echo "Task not filtered out"

  matrix-status:
    if: ${{ always() }}
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - name: Successful
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing
        if: ${{ (contains(needs.*.result, 'failure')) }}
        run: exit 1
