
on:
  merge_group:
<<<<<<< Updated upstream
    # keep workflow specific if GH Actions adds more types in the future
    types: ["checks-requested"]
=======
>>>>>>> Stashed changes
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev", "*"]
  workflow_dispatch:

    
jobs:
  build:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - name: Filtered
      - run: echo "Skipped in merge queue"
  build:
    if: ${{ github.event_name != 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - name: Intermediate
        run: echo "Intermediate job was not skipped"
