
on:
  merge_group:
    # keep workflow specific if GH Actions adds more types in the future
    types: ["checks-requested"]
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev", "*"]
  workflow_dispatch:

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # ------------ Status check setup ------------
      # ------------ Skip on merge queue -----------
      - name: Setup
        if: ${{ always() && github.event_name != 'merge_group' }}
        run: echo "Running status check job"
      # --------------------------------------------

      - name: Intermediate
        run: echo "Intermediate job was not skipped"

      # ------------ Status check report ------------
      # ------------ Skip on merge queue ------------
      - name: Report
        if: ${{ (always() && github.event_name == 'merge_group') || github.event_name != 'merge_group' }}
        run: echo "Completed or skipped status check job"
      # ---------------------------------------------
